In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('sonardataset.csv')

In [3]:
df.shape

(208, 61)

In [4]:
df.head()

x_1     x_2     x_3     x_4     x_5     x_6     x_7     x_8     x_9  \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

     x_10  ...    x_52    x_53    x_54    x_55    x_56    x_57    x_58  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

     x_59    x_60  Y  
0  0.0090  0.0032  R  
1  0.0052  0.0044  R  
2  0.0095  0.0078  R  
3  0.0040  0.0117  R  
4  0.0107  0.0094  R  

[5 rows x 61 columns]

In [5]:
### missing values
df.isnull().sum()

x_1     0
x_2     0
x_3     0
x_4     0
x_5     0
       ..
x_57    0
x_58    0
x_59    0
x_60    0
Y       0
Length: 61, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x_1     208 non-null    float64
 1   x_2     208 non-null    float64
 2   x_3     208 non-null    float64
 3   x_4     208 non-null    float64
 4   x_5     208 non-null    float64
 5   x_6     208 non-null    float64
 6   x_7     208 non-null    float64
 7   x_8     208 non-null    float64
 8   x_9     208 non-null    float64
 9   x_10    208 non-null    float64
 10  x_11    208 non-null    float64
 11  x_12    208 non-null    float64
 12  x_13    208 non-null    float64
 13  x_14    208 non-null    float64
 14  x_15    208 non-null    float64
 15  x_16    208 non-null    float64
 16  x_17    208 non-null    float64
 17  x_18    208 non-null    float64
 18  x_19    208 non-null    float64
 19  x_20    208 non-null    float64
 20  x_21    208 non-null    float64
 21  x_22    208 non-null    float64
 22  x_

In [7]:
df.describe()

x_1         x_2         x_3         x_4         x_5         x_6  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570   
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025   
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150   
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

              x_7         x_8         x_9        x_10  ...        x_51  \
count  208.000000  208.000000  208.000000  208.000000  ...  208.000000   
mean     0.121747    0.134799    0.178003    0.208259  ...    0.016069   
std      0.061788    0.085152    0.118387    0.134416  ...    0.012008   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080900    0.080425    0.097025    0.111275  ...    0.008425   
50%      0.106950    0.112100    0.152250    0.182400  ...    0.013900   
75%      0.154000    0.169600    0.233425    0.268700  ...    0.020825   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

             x_52        x_53        x_54        x_55        x_56        x_57  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.013420    0.010709    0.010941    0.009290    0.008222    0.007820   
std      0.009634    0.007060    0.007301    0.007088    0.005736    0.005785   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007275    0.005075    0.005375    0.004150    0.004400    0.003700   
50%      0.011400    0.009550    0.009300    0.007500    0.006850    0.005950   
75%      0.016725    0.014900    0.014500    0.012100    0.010575    0.010425   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

             x_58        x_59        x_60  
count  208.000000  208.000000  208.000000  
mean     0.007949    0.007941    0.006507  
std      0.006470    0.006181    0.005031  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003675    0.003100  
50%      0.005800    0.006400    0.005300  
75%      0.010350    0.010325    0.008525  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

In [8]:
from sklearn.preprocessing import StandardScaler, LabelEncoder              
from sklearn.model_selection import train_test_split

In [9]:
x=df.drop('Y',axis=1)
y=df['Y']

In [10]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_scaled

array([[-0.39955135, -0.04064823, -0.02692565, ...,  0.06987027,
         0.17167808, -0.65894689],
       [ 0.70353822,  0.42163039,  1.05561832, ..., -0.47240644,
        -0.44455424, -0.41985233],
       [-0.12922901,  0.60106749,  1.72340448, ...,  1.30935987,
         0.25276128,  0.25758223],
       ...,
       [ 1.00438083,  0.16007801, -0.67384349, ...,  0.90652575,
        -0.03913824, -0.67887143],
       [ 0.04953255, -0.09539176,  0.13480381, ..., -0.00759783,
        -0.70402047, -0.34015415],
       [-0.13794908, -0.06497869, -0.78861924, ..., -0.6738235 ,
        -0.29860448,  0.99479044]])

In [11]:
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)
y_encoded

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.2, random_state=42)                        # data split into train and test
x_train, x_test, y_train, y_test

(array([[-0.45187181, -0.04368954,  1.34255769, ..., -0.34845747,
         -0.185088  , -0.81834326],
        [-0.45623184, -0.1166809 , -0.70514597, ...,  0.55017249,
          1.841992  ,  1.83162138],
        [ 0.33293501,  0.05667358, -0.31647355, ..., -0.19352127,
         -0.0229216 ,  0.05833677],
        ...,
        [-0.13794908, -0.58504214, -0.48081155, ..., -1.10764486,
         -0.57428736,  0.23765769],
        [ 0.44629599,  0.1083758 ,  0.02002807, ..., -0.17802765,
         -0.4283376 ,  0.43690315],
        [ 1.28778329,  2.51100814,  2.16424769, ...,  0.33326181,
          2.4095744 ,  1.17411135]]),
 array([[ 0.05825262, -0.06497869, -0.58515314, ..., -0.58086178,
         -0.39590432, -0.8781169 ],
        [ 0.02773236,  0.70143061,  0.55217016, ..., -0.47240644,
          1.95550848,  0.1579595 ],
        [-0.66551366, -0.49380294, -0.9112206 , ..., -0.31747023,
         -0.65537055, -0.34015415],
        ...,
        [-0.03766821,  0.65276971,  0.5678214 , ..., -

In [13]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [14]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

In [16]:
y_train_one_hot = to_categorical(y_train)
y_test_one_hot = to_categorical(y_test)

In [17]:
model = Sequential()
model.add(Dense(128, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(y_train_one_hot.shape[1], activation='softmax'))

In [18]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [19]:
history = model.fit(x_train, y_train_one_hot, epochs=10, batch_size=32, validation_data=(x_test, y_test_one_hot))

Epoch 1/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 136ms/step - accuracy: 0.5663 - loss: 0.7442 - val_accuracy: 0.8095 - val_loss: 0.5811
Epoch 2/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7711 - loss: 0.5504 - val_accuracy: 0.8095 - val_loss: 0.4536
Epoch 3/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8373 - loss: 0.4496 - val_accuracy: 0.7619 - val_loss: 0.4639
Epoch 4/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8735 - loss: 0.3886 - val_accuracy: 0.7619 - val_loss: 0.4968
Epoch 5/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8976 - loss: 0.3352 - val_accuracy: 0.7857 - val_loss: 0.4498
Epoch 6/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9337 - loss: 0.2796 - val_accuracy: 0.7857 - val_loss: 0.3985
Epoch 7/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9518 - loss: 0.2363 - val_accuracy: 0.8095 - val_loss: 0.3830
Epoch 8/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9578 - loss: 0.2090 - val_accuracy: 0.8571 - val_loss: 0.3796

In [20]:
loss, accuracy = model.evaluate(x_test, y_test_one_hot)
print("\nTest Accuracy: {:.2f}%".format(accuracy * 100))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8810 - loss: 0.3440

Test Accuracy: 88.10%


In [21]:
pip install tensorflow scikit-learn keras-tuner

In [22]:
import keras_tuner as kt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [23]:
def create_model(hp):
    model = Sequential()
    model.add(Dense(units=hp.Int('units', min_value=32, max_value=128, step=32), input_dim=x_train.shape[1], activation='relu'))
    model.add(Dense(y_train_one_hot.shape[1], activation='softmax'))

    model.compile(
        loss='categorical_crossentropy',
        optimizer=Adam(learning_rate=hp.Choice('learning_rate', values=[0.001, 0.01, 0.1])),
        metrics=['accuracy']
    )
    return model

In [24]:
tuner = kt.Hyperband(
    create_model,
    objective='val_accuracy',
    max_epochs=10,
    factor=3,
    directory='keras_tuner',
    project_name='alphabet_model'
)

In [25]:
tuner.search(x_train, y_train_one_hot, epochs=10, validation_data=(x_test, y_test_one_hot))

Trial 18 Complete [00h 00m 04s]
val_accuracy: 0.9523809552192688

Best val_accuracy So Far: 0.9523809552192688
Total elapsed time: 00h 01m 02s


In [26]:
best_model = tuner.get_best_models(num_models=1)[0]
loss, accuracy = best_model.evaluate(x_test, y_test_one_hot)
print("\nTest Accuracy with Best Hyperparameters: {:.2f}%".format(accuracy * 100))

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.9524 - loss: 0.1727 

Test Accuracy with Best Hyperparameters: 95.24%


In [27]:
from sklearn.metrics import classification_report

# Get predictions
y_pred = model.predict(x_test)

# Convert predictions and true labels back from one-hot encoding
y_pred_labels = encoder.inverse_transform(y_pred.argmax(axis=1))
y_test_labels = encoder.inverse_transform(y_test)

# Print classification report
print("\nClassification Report:")
print(classification_report(y_test_labels, y_pred_labels))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Classification Report:
              precision    recall  f1-score   support

           M       0.96      0.85      0.90        26
           R       0.79      0.94      0.86        16

    accuracy                           0.88        42
   macro avg       0.87      0.89      0.88        42
weighted avg       0.89      0.88      0.88        42



In [28]:
### it is having 90% of accuracy an